// Mocks generated by Mockito 5.4.6 from annotations
// in hive_observation/test/widgets/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i13;

import 'package:hive_observation/models/models.dart' as _i7;
import 'package:hive_observation/models/notification_model.dart' as _i9;
import 'package:hive_observation/providers/app_state.dart' as _i8;
import 'package:hive_observation/providers/chat_provider.dart' as _i3;
import 'package:hive_observation/providers/civilization_provider.dart' as _i5;
import 'package:hive_observation/providers/feed_provider.dart' as _i2;
import 'package:hive_observation/providers/notification_provider.dart' as _i4;
import 'package:hive_observation/services/api_service.dart' as _i14;
import 'package:hive_observation/services/cache_service.dart' as _i12;
import 'package:hive_observation/services/websocket_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFeedProvider_0 extends _i1.SmartFake implements _i2.FeedProvider {
  _FakeFeedProvider_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatProvider_1 extends _i1.SmartFake implements _i3.ChatProvider {
  _FakeChatProvider_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationProvider_2 extends _i1.SmartFake
    implements _i4.NotificationProvider {
  _FakeNotificationProvider_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCivilizationProvider_3 extends _i1.SmartFake
    implements _i5.CivilizationProvider {
  _FakeCivilizationProvider_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebSocketService_4 extends _i1.SmartFake
    implements _i6.WebSocketService {
  _FakeWebSocketService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePost_5 extends _i1.SmartFake implements _i7.Post {
  _FakePost_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppUser_6 extends _i1.SmartFake implements _i7.AppUser {
  _FakeAppUser_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComment_7 extends _i1.SmartFake implements _i7.Comment {
  _FakeComment_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatMessage_8 extends _i1.SmartFake implements _i7.ChatMessage {
  _FakeChatMessage_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectMessage_9 extends _i1.SmartFake implements _i7.DirectMessage {
  _FakeDirectMessage_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBotProfile_10 extends _i1.SmartFake implements _i7.BotProfile {
  _FakeBotProfile_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppState extends _i1.Mock implements _i8.AppState {
  MockAppState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FeedProvider get feedProvider =>
      (super.noSuchMethod(
            Invocation.getter(#feedProvider),
            returnValue: _FakeFeedProvider_0(
              this,
              Invocation.getter(#feedProvider),
            ),
          )
          as _i2.FeedProvider);

  @override
  _i3.ChatProvider get chatProvider =>
      (super.noSuchMethod(
            Invocation.getter(#chatProvider),
            returnValue: _FakeChatProvider_1(
              this,
              Invocation.getter(#chatProvider),
            ),
          )
          as _i3.ChatProvider);

  @override
  _i4.NotificationProvider get notificationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#notificationProvider),
            returnValue: _FakeNotificationProvider_2(
              this,
              Invocation.getter(#notificationProvider),
            ),
          )
          as _i4.NotificationProvider);

  @override
  _i5.CivilizationProvider get civilizationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#civilizationProvider),
            returnValue: _FakeCivilizationProvider_3(
              this,
              Invocation.getter(#civilizationProvider),
            ),
          )
          as _i5.CivilizationProvider);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  int get queuedActionsCount =>
      (super.noSuchMethod(
            Invocation.getter(#queuedActionsCount),
            returnValue: 0,
          )
          as int);

  @override
  _i6.WebSocketService get websocket =>
      (super.noSuchMethod(
            Invocation.getter(#websocket),
            returnValue: _FakeWebSocketService_4(
              this,
              Invocation.getter(#websocket),
            ),
          )
          as _i6.WebSocketService);

  @override
  List<_i7.Post> get posts =>
      (super.noSuchMethod(Invocation.getter(#posts), returnValue: <_i7.Post>[])
          as List<_i7.Post>);

  @override
  bool get isLoadingFeed =>
      (super.noSuchMethod(Invocation.getter(#isLoadingFeed), returnValue: false)
          as bool);

  @override
  bool get hasMorePosts =>
      (super.noSuchMethod(Invocation.getter(#hasMorePosts), returnValue: false)
          as bool);

  @override
  List<_i7.Community> get communities =>
      (super.noSuchMethod(
            Invocation.getter(#communities),
            returnValue: <_i7.Community>[],
          )
          as List<_i7.Community>);

  @override
  List<_i7.ChatMessage> get chatMessages =>
      (super.noSuchMethod(
            Invocation.getter(#chatMessages),
            returnValue: <_i7.ChatMessage>[],
          )
          as List<_i7.ChatMessage>);

  @override
  bool get isLoadingChat =>
      (super.noSuchMethod(Invocation.getter(#isLoadingChat), returnValue: false)
          as bool);

  @override
  List<_i7.Conversation> get conversations =>
      (super.noSuchMethod(
            Invocation.getter(#conversations),
            returnValue: <_i7.Conversation>[],
          )
          as List<_i7.Conversation>);

  @override
  List<_i7.DirectMessage> get directMessages =>
      (super.noSuchMethod(
            Invocation.getter(#directMessages),
            returnValue: <_i7.DirectMessage>[],
          )
          as List<_i7.DirectMessage>);

  @override
  bool get isTyping =>
      (super.noSuchMethod(Invocation.getter(#isTyping), returnValue: false)
          as bool);

  @override
  Map<String, String> get communityTypingUsers =>
      (super.noSuchMethod(
            Invocation.getter(#communityTypingUsers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  List<_i9.NotificationModel> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: <_i9.NotificationModel>[],
          )
          as List<_i9.NotificationModel>);

  @override
  int get unreadNotificationCount =>
      (super.noSuchMethod(
            Invocation.getter(#unreadNotificationCount),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadFeed({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadFeed, [], {#refresh: refresh}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> likePost(
    _i7.Post? post, {
    _i7.ReactionType? reactionType = _i7.ReactionType.like,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [post], {#reactionType: reactionType}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> commentOnPost(_i7.Post? post, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#commentOnPost, [post, content]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.Post> createPost({
    required String? content,
    required String? communityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #communityId: communityId,
            }),
            returnValue: _i10.Future<_i7.Post>.value(
              _FakePost_5(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #communityId: communityId,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.Post>);

  @override
  _i10.Future<void> loadCommunities() =>
      (super.noSuchMethod(
            Invocation.method(#loadCommunities, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void selectCommunity(_i7.Community? community) => super.noSuchMethod(
    Invocation.method(#selectCommunity, [community]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> loadCommunityChat(String? communityId) =>
      (super.noSuchMethod(
            Invocation.method(#loadCommunityChat, [communityId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendChatMessage(String? content, {String? replyToId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendChatMessage,
              [content],
              {#replyToId: replyToId},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadConversations() =>
      (super.noSuchMethod(
            Invocation.method(#loadConversations, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> selectBot(_i7.BotProfile? bot) =>
      (super.noSuchMethod(
            Invocation.method(#selectBot, [bot]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendDirectMessage(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#sendDirectMessage, [content]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i7.BotProfile>> loadBots({
    String? communityId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadBots, [], {
              #communityId: communityId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i10.Future<List<_i7.BotProfile>>.value(
              <_i7.BotProfile>[],
            ),
          )
          as _i10.Future<List<_i7.BotProfile>>);

  @override
  _i10.Future<void> loadNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#loadNotifications, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> markNotificationRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationRead, [notificationId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> markAllNotificationsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsRead, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> refreshUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUnreadCount, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> getCacheSize() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheSize, []),
            returnValue: _i10.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#getCacheSize, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> clearExpiredCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearExpiredCache, []),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<void> invalidateFeedCache() =>
      (super.noSuchMethod(
            Invocation.method(#invalidateFeedCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> invalidateChatCache(String? communityId) =>
      (super.noSuchMethod(
            Invocation.method(#invalidateChatCache, [communityId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> invalidateDMCache(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#invalidateDMCache, [conversationId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> invalidateConversationsCache() =>
      (super.noSuchMethod(
            Invocation.method(#invalidateConversationsCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i12.CacheMetadata>> getCacheMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMetadata, []),
            returnValue: _i10.Future<List<_i12.CacheMetadata>>.value(
              <_i12.CacheMetadata>[],
            ),
          )
          as _i10.Future<List<_i12.CacheMetadata>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i14.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i7.AppUser> registerUser(
    String? deviceId,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [deviceId, displayName]),
            returnValue: _i10.Future<_i7.AppUser>.value(
              _FakeAppUser_6(
                this,
                Invocation.method(#registerUser, [deviceId, displayName]),
              ),
            ),
          )
          as _i10.Future<_i7.AppUser>);

  @override
  _i10.Future<List<_i7.Post>> getFeed({
    String? userId,
    String? communityId,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFeed, [], {
              #userId: userId,
              #communityId: communityId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i10.Future<List<_i7.Post>>.value(<_i7.Post>[]),
          )
          as _i10.Future<List<_i7.Post>>);

  @override
  _i10.Future<_i7.Post> getPost(String? postId, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId], {#userId: userId}),
            returnValue: _i10.Future<_i7.Post>.value(
              _FakePost_5(
                this,
                Invocation.method(#getPost, [postId], {#userId: userId}),
              ),
            ),
          )
          as _i10.Future<_i7.Post>);

  @override
  _i10.Future<Map<String, dynamic>> likePost(
    String? postId,
    String? userId, {
    bool? isBot = false,
    String? reactionType = 'like',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #likePost,
              [postId, userId],
              {#isBot: isBot, #reactionType: reactionType},
            ),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> unlikePost(
    String? postId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unlikePost, [postId, userId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i7.Comment> createComment(
    String? postId,
    String? userId,
    String? content, {
    bool? isBot = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createComment,
              [postId, userId, content],
              {#isBot: isBot},
            ),
            returnValue: _i10.Future<_i7.Comment>.value(
              _FakeComment_7(
                this,
                Invocation.method(
                  #createComment,
                  [postId, userId, content],
                  {#isBot: isBot},
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Comment>);

  @override
  _i10.Future<List<_i7.Comment>> getComments(
    String? postId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getComments,
              [postId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i10.Future<List<_i7.Comment>>.value(<_i7.Comment>[]),
          )
          as _i10.Future<List<_i7.Comment>>);

  @override
  _i10.Future<List<_i7.Author>> getLikers(
    String? postId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLikers,
              [postId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i10.Future<List<_i7.Author>>.value(<_i7.Author>[]),
          )
          as _i10.Future<List<_i7.Author>>);

  @override
  _i10.Future<_i7.Post> createPost({
    required String? userId,
    required String? communityId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #userId: userId,
              #communityId: communityId,
              #content: content,
            }),
            returnValue: _i10.Future<_i7.Post>.value(
              _FakePost_5(
                this,
                Invocation.method(#createPost, [], {
                  #userId: userId,
                  #communityId: communityId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.Post>);

  @override
  _i10.Future<List<_i7.ChatMessage>> getCommunityChat(
    String? communityId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCommunityChat,
              [communityId],
              {#limit: limit},
            ),
            returnValue: _i10.Future<List<_i7.ChatMessage>>.value(
              <_i7.ChatMessage>[],
            ),
          )
          as _i10.Future<List<_i7.ChatMessage>>);

  @override
  _i10.Future<_i7.ChatMessage> sendCommunityMessage(
    String? communityId,
    String? userId,
    String? content, {
    String? replyToId,
    bool? isBot = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendCommunityMessage,
              [communityId, userId, content],
              {#replyToId: replyToId, #isBot: isBot},
            ),
            returnValue: _i10.Future<_i7.ChatMessage>.value(
              _FakeChatMessage_8(
                this,
                Invocation.method(
                  #sendCommunityMessage,
                  [communityId, userId, content],
                  {#replyToId: replyToId, #isBot: isBot},
                ),
              ),
            ),
          )
          as _i10.Future<_i7.ChatMessage>);

  @override
  _i10.Future<List<_i7.Conversation>> getConversations(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [userId]),
            returnValue: _i10.Future<List<_i7.Conversation>>.value(
              <_i7.Conversation>[],
            ),
          )
          as _i10.Future<List<_i7.Conversation>>);

  @override
  _i10.Future<List<_i7.DirectMessage>> getDirectMessages(
    String? conversationId,
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDirectMessages,
              [conversationId, userId],
              {#limit: limit},
            ),
            returnValue: _i10.Future<List<_i7.DirectMessage>>.value(
              <_i7.DirectMessage>[],
            ),
          )
          as _i10.Future<List<_i7.DirectMessage>>);

  @override
  _i10.Future<_i7.DirectMessage> sendDirectMessage(
    String? userId,
    String? receiverId,
    String? content, {
    bool? isBot = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendDirectMessage,
              [userId, receiverId, content],
              {#isBot: isBot},
            ),
            returnValue: _i10.Future<_i7.DirectMessage>.value(
              _FakeDirectMessage_9(
                this,
                Invocation.method(
                  #sendDirectMessage,
                  [userId, receiverId, content],
                  {#isBot: isBot},
                ),
              ),
            ),
          )
          as _i10.Future<_i7.DirectMessage>);

  @override
  _i10.Future<List<_i7.Community>> getCommunities() =>
      (super.noSuchMethod(
            Invocation.method(#getCommunities, []),
            returnValue: _i10.Future<List<_i7.Community>>.value(
              <_i7.Community>[],
            ),
          )
          as _i10.Future<List<_i7.Community>>);

  @override
  _i10.Future<List<_i7.BotProfile>> getBots({
    String? communityId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBots, [], {
              #communityId: communityId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i10.Future<List<_i7.BotProfile>>.value(
              <_i7.BotProfile>[],
            ),
          )
          as _i10.Future<List<_i7.BotProfile>>);

  @override
  _i10.Future<_i7.BotProfile> getBotProfile(String? botId) =>
      (super.noSuchMethod(
            Invocation.method(#getBotProfile, [botId]),
            returnValue: _i10.Future<_i7.BotProfile>.value(
              _FakeBotProfile_10(
                this,
                Invocation.method(#getBotProfile, [botId]),
              ),
            ),
          )
          as _i10.Future<_i7.BotProfile>);

  @override
  _i10.Future<Map<String, dynamic>> initializePlatform({
    int? numCommunities = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializePlatform, [], {
              #numCommunities: numCommunities,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<bool> healthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#healthCheck, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> getBotIntelligence(String? botId) =>
      (super.noSuchMethod(
            Invocation.method(#getBotIntelligence, [botId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<dynamic>> getBotSkills(String? botId) =>
      (super.noSuchMethod(
            Invocation.method(#getBotSkills, [botId]),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> triggerBotReflection(String? botId) =>
      (super.noSuchMethod(
            Invocation.method(#triggerBotReflection, [botId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> triggerBotEvolution(String? botId) =>
      (super.noSuchMethod(
            Invocation.method(#triggerBotEvolution, [botId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> triggerBotSelfCoding(
    String? botId, {
    String? whatToImprove = 'general intelligence',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #triggerBotSelfCoding,
              [botId],
              {#whatToImprove: whatToImprove},
            ),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getPlatformIntelligence() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformIntelligence, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<dynamic>> getRecentEvolutionActivity({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentEvolutionActivity, [], {#limit: limit}),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getGitHubStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubStatus, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getCivilizationStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCivilizationStats, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getCurrentEra() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentEra, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<dynamic>> getCivilizationTimeline({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCivilizationTimeline, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> getLivingBeings({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getLivingBeings, [], {#limit: limit}),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> getDepartedBeings({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getDepartedBeings, [], {#limit: limit}),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> getActiveRituals() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveRituals, []),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> getCulturalMovements() =>
      (super.noSuchMethod(
            Invocation.method(#getCulturalMovements, []),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getBeingProfile(String? beingId) =>
      (super.noSuchMethod(
            Invocation.method(#getBeingProfile, [beingId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<dynamic>> getBeingRelationships(String? beingId) =>
      (super.noSuchMethod(
            Invocation.method(#getBeingRelationships, [beingId]),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
