// Mocks generated by Mockito 5.4.6 from annotations
// in hive_observation/test/widgets/notifications_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:hive_observation/models/models.dart' as _i2;
import 'package:hive_observation/models/notification_model.dart' as _i4;
import 'package:hive_observation/providers/feed_provider.dart' as _i7;
import 'package:hive_observation/providers/notification_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePost_0 extends _i1.SmartFake implements _i2.Post {
  _FakePost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationProvider extends _i1.Mock
    implements _i3.NotificationProvider {
  MockNotificationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.NotificationModel> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: <_i4.NotificationModel>[],
          )
          as List<_i4.NotificationModel>);

  @override
  int get unreadNotificationCount =>
      (super.noSuchMethod(
            Invocation.getter(#unreadNotificationCount),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setCurrentUserId(String? userId) => super.noSuchMethod(
    Invocation.method(#setCurrentUserId, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> loadNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#loadNotifications, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markNotificationRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationRead, [notificationId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markAllNotificationsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsRead, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUnreadCount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void disposeService() => super.noSuchMethod(
    Invocation.method(#disposeService, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeedProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedProvider extends _i1.Mock implements _i7.FeedProvider {
  MockFeedProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Post> get posts =>
      (super.noSuchMethod(Invocation.getter(#posts), returnValue: <_i2.Post>[])
          as List<_i2.Post>);

  @override
  bool get isLoadingFeed =>
      (super.noSuchMethod(Invocation.getter(#isLoadingFeed), returnValue: false)
          as bool);

  @override
  bool get hasMorePosts =>
      (super.noSuchMethod(Invocation.getter(#hasMorePosts), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setCurrentUserId(String? userId) => super.noSuchMethod(
    Invocation.method(#setCurrentUserId, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedCommunityId(String? communityId) => super.noSuchMethod(
    Invocation.method(#setSelectedCommunityId, [communityId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addPost(_i2.Post? post) => super.noSuchMethod(
    Invocation.method(#addPost, [post]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePostLikeCount(String? postId, int? likeCount) =>
      super.noSuchMethod(
        Invocation.method(#updatePostLikeCount, [postId, likeCount]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadFeed({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadFeed, [], {#refresh: refresh}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> likePost(
    _i2.Post? post, {
    _i2.ReactionType? reactionType = _i2.ReactionType.like,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [post], {#reactionType: reactionType}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> commentOnPost(_i2.Post? post, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#commentOnPost, [post, content]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Post> createPost({
    required String? content,
    required String? communityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #communityId: communityId,
            }),
            returnValue: _i5.Future<_i2.Post>.value(
              _FakePost_0(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #communityId: communityId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Post>);

  @override
  _i5.Future<void> loadCachedFeed() =>
      (super.noSuchMethod(
            Invocation.method(#loadCachedFeed, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
